# Generated by Django 5.2.6 on 2025-09-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira o nome do jogo', max_length=100)),
                ('genero', models.EmailField(help_text='Insira o genero do jogo', max_length=254)),
                ('desenvolvedora', models.EmailField(help_text='Insira a desenvolvedora do jogo', max_length=254)),
                ('dtNasc', models.DateField(help_text='Data de lancamento no formato DD/MM/AAAA', verbose_name='Data de lancamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira o nome', max_length=100)),
                ('email', models.EmailField(help_text='Insira o email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(help_text='Insira a nota')),
                ('descricao', models.CharField(help_text='Insira a descricao', max_length=256)),
                ('id_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerboxd.jogo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamerboxd.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_jogo', 'id_usuario'), name='unique_jogo_usuario_combination')],
            },
        ),
    ]
