# Generated by Django 5.2.6 on 2025-09-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerboxd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='dtNasc',
            new_name='dtLanc',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='desenvolvedora',
            field=models.CharField(help_text='Insira a desenvolvedora do jogo', max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.CharField(help_text='Insira o genero do jogo', max_length=20),
        ),
    ]
